//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string username { get; set; }
        public string password { get; set; }
        public int customer_id { get; set; }
        public Nullable<bool> is_admin { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
    }
}
