//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenBay()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int MaCB { get; set; }
        public Nullable<int> MaMB { get; set; }
        public Nullable<int> MaTBay { get; set; }
        public Nullable<System.DateTime> NgayGio { get; set; }
        public Nullable<int> ThoiGianBay { get; set; }
        public Nullable<int> SoLuongGheHang1 { get; set; }
        public Nullable<int> SoLuongGheHang2 { get; set; }
        public Nullable<int> SoLuongGheHang3 { get; set; }
        public string TinhTrang { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual MayBay MayBay { get; set; }
        public virtual TuyenBay TuyenBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
