//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenBay
    {
        public string MaCB { get; set; }
        public string MaMB { get; set; }
        public string MaTBay { get; set; }
        public Nullable<System.DateTime> NgayGio { get; set; }
        public string ThoiGianBay { get; set; }
        public Nullable<int> SoLuongGheHang1 { get; set; }
        public Nullable<int> SoLuongGheHang2 { get; set; }
        public Nullable<int> SoLuongGheHang3 { get; set; }
        public string TinhTrang { get; set; }
    }
}
