//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guest()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Id_Guest { get; set; }
        public string HoTenG { get; set; }
        public string EmailG { get; set; }
        public string SoDienThoaiG { get; set; }
        public Nullable<System.DateTime> NgaySinhG { get; set; }
        public string SoHoChieu { get; set; }
        public string QuocGiaCap { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
