//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayBay
    {
        public string MaMB { get; set; }
        public string LoaiMayBay { get; set; }
    }
}
