//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string IDNV { get; set; }
        public string MaCV { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string TenNV { get; set; }
        public string SDT_NV { get; set; }
        public string Email_NV { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    }
}
