//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int payment_id { get; set; }
        public Nullable<int> booking_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string payment_method { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string payment_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Booking Booking { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
