//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phi
    {
        public string MaPhi { get; set; }
        public string TenPhi { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string DonVi { get; set; }
    }
}
