//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public string MaVe { get; set; }
        public string MaCB { get; set; }
        public string MaHV { get; set; }
        public string IDKH { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<double> GiaVe { get; set; }
        public string CCCD { get; set; }
        public string XacNhan { get; set; }
    
        public virtual ChuyenBay ChuyenBay { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
